spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  h2:
    console:
      enabled: true
#    enable access from remote location
    settings:
      web-allow-others: true